// client-only radar analysis over FIXTURE_DIFF: 12 units across all six lanes, with
// deterministic evidence, jev distributions, packet provenance, cache, and stale/blocked cases.

const dist = (worthy, impact, sufficient) => [
  { name: "Review worthy", pct: worthy },
  { name: "Material impact", pct: impact },
  { name: "Evidence sufficient", pct: sufficient },
];
const packet = (paths, bytes, lines, redactions = 0, exclusions = []) => ({ paths, bytes, lines, redactions, exclusions });

export const FIXTURE_META = {
  generatedAt: new Date(Date.now() - 3 * 60000).toISOString(),
  provider: "openrouter", model: "jev-1.13", questionSet: "radar-q1",
  totalUnits: 12,
};

export const FIXTURE_UNITS = [
  { id: "u1", file: "src/server/sessionHandlers.ts", hunk: 0, line: 46, lane: "verified",
    title: "stopSession · line 46", chip: "tsc · TS2532", attention: 82, remote: true,
    summary: "A new compiler result reports possibly-undefined access on the changed line; the missing-session path now throws instead of returning.",
    provenance: ["tsc TS2532 on new line 46", "changed hunk intersects the diagnostic", "jev 0.82 attention"],
    distributions: dist(82, 71, 78), sufficiency: "sufficient", context: { lines: 34, complete: true },
    truncation: false, redaction: false, cache: { state: "live", ms: 186 },
    packet: packet(["src/server/sessionHandlers.ts"], 4210, 34) },
  { id: "u2", file: "src/server/sessionHandlers.ts", hunk: 0, line: 48, lane: "boundary",
    title: "stopSession · lines 47–49", chip: "boundary · process lifetime", attention: 64, remote: true,
    summary: "The change spans a configured process-lifetime boundary: cleanup now kills a child process and removes persisted state in the same path.",
    provenance: ["process-lifetime boundary rule", "child.kill() + removeSession() on the change", "jev 0.64 attention"],
    distributions: dist(64, 69, 72), sufficiency: "sufficient", context: { lines: 34, complete: true },
    truncation: false, redaction: false, cache: { state: "live", ms: 186 },
    packet: packet(["src/server/sessionHandlers.ts"], 4210, 34) },
  { id: "u3", file: "src/core/reviewRecords.ts", hunk: 0, line: 132, lane: "boundary",
    title: "writeRecord · lines 130–133", chip: "boundary · persisted state", attention: 58, remote: true,
    summary: "The change crosses a data-durability boundary: a direct write became a temp-file write plus rename touching persisted review records.",
    provenance: ["persisted-state boundary rule", "writeFileSync + renameSync on the change", "jev 0.58 attention"],
    distributions: dist(58, 61, 66), sufficiency: "partial", context: { lines: 40, complete: true },
    truncation: false, redaction: false, cache: { state: "live", ms: 204 },
    packet: packet(["src/core/reviewRecords.ts"], 5120, 40) },
  { id: "u4", file: "src/core/reviewRecords.ts", hunk: 0, line: 130, lane: "attention",
    title: "writeRecord · line 130", chip: "jev · context uncertainty", attention: 71, remote: true,
    summary: "No deterministic finding on this line; jev raised it because the surrounding record shape is only partially visible in the transmitted context.",
    provenance: ["no analyzer result", "partial context around the change", "jev 0.71 attention"],
    distributions: dist(71, 44, 52), sufficiency: "partial", context: { lines: 40, complete: false },
    truncation: true, redaction: false, cache: { state: "live", ms: 204 },
    packet: packet(["src/core/reviewRecords.ts"], 5120, 40, 0, ["prior record body over cap"]) },
  { id: "u5", file: "src/client/reviewSync.js", hunk: 0, line: 47, lane: "attention", stale: true,
    title: "useReviewSync · lines 46–48", chip: "jev · lifecycle uncertainty", attention: 69, remote: true,
    summary: "A generation guard was added inside an async poll callback; jev flagged lifecycle uncertainty around the closure.",
    provenance: ["no analyzer result", "async closure over a mutable ref", "jev 0.69 attention"],
    distributions: dist(69, 48, 55), sufficiency: "partial", context: { lines: 28, complete: true },
    truncation: false, redaction: false, cache: { state: "live", ms: 173 },
    packet: packet(["src/client/reviewSync.js"], 3640, 28) },
  { id: "u6", file: "src/client/reviewSync.js", hunk: 0, line: 46, lane: "routine",
    title: "useReviewSync · line 46", chip: "no higher lane", attention: null, remote: false,
    summary: "A local variable capture with no analyzer result, boundary, or raised attention; kept in routine review.",
    provenance: ["no analyzer result", "no configured boundary", "jev did not raise the unit"],
    distributions: null, sufficiency: "sufficient", context: { lines: 28, complete: true },
    truncation: false, redaction: false, cache: { state: "live", ms: 173 },
    packet: packet(["src/client/reviewSync.js"], 3640, 28) },
  { id: "u7", file: "tests/sessions.test.ts", hunk: 0, line: 4, lane: "routine",
    title: "sessions.test.ts · line 4", chip: "test coverage", attention: null, remote: false,
    summary: "New test coverage for the changed behavior; no analyzer result or boundary, kept in routine review.",
    provenance: ["new test file", "no analyzer result", "no configured boundary"],
    distributions: null, sufficiency: "sufficient", context: { lines: 8, complete: true },
    truncation: false, redaction: false, cache: { state: "live", ms: 91 },
    packet: packet(["tests/sessions.test.ts"], 620, 8) },
  { id: "u8", file: "src/client/motion.css", hunk: 0, line: 7, lane: "noise",
    title: "motion.css · line 7", chip: "moved lines", attention: null, remote: false,
    summary: "Two token declarations were reordered with no value change; classified as noise but still reachable.",
    provenance: ["identical text on both sides", "move detected", "not transmitted to jev"],
    distributions: null, sufficiency: "sufficient", context: { lines: 6, complete: true },
    truncation: false, redaction: false, cache: { state: "live", ms: 44 },
    packet: packet(["src/client/motion.css"], 240, 6) },
  { id: "u9", file: "src/client/motion.css", hunk: 0, line: 8, lane: "noise",
    title: "motion.css · line 8", chip: "moved lines", attention: null, remote: false,
    summary: "Reordered token declaration with no value change; classified as noise but still reachable.",
    provenance: ["identical text on both sides", "move detected", "not transmitted to jev"],
    distributions: null, sufficiency: "sufficient", context: { lines: 6, complete: true },
    truncation: false, redaction: false, cache: { state: "live", ms: 44 },
    packet: packet(["src/client/motion.css"], 240, 6) },
  { id: "u10", file: "tests/sessions.test.ts", hunk: 0, line: 8, lane: "blocker",
    title: "sessions.test.ts · line 8", chip: "context over cap", attention: null, remote: false,
    summary: "Required context could not be assembled: the referenced fixture exceeds the packet cap, so this unit was not transmitted.",
    blockedReason: "required context (tests/fixtures/dump.json, 3.2 MB) exceeds the 2 MB packet cap — not transmitted",
    provenance: ["deterministic scan only", "context assembly failed", "no remote analysis"],
    distributions: null, sufficiency: "insufficient", context: { lines: 0, complete: false },
    truncation: true, redaction: false, cache: { state: "n/a", ms: 0 },
    packet: packet(["tests/sessions.test.ts", "tests/fixtures/dump.json"], 0, 0, 0, ["dump.json 3.2 MB over cap"]) },
  { id: "u11", file: "src/config/providerKeys.ts", hunk: 0, line: 14, lane: "blocker",
    title: "providerKeys.ts · line 14", chip: "secret redacted", attention: null, remote: false,
    summary: "The added line matched a secret pattern and was redacted; the unit was withheld from transmission to avoid unsafe outbound content.",
    blockedReason: "line matches an openrouter key pattern — redacted and withheld from transmission",
    provenance: ["secret pattern match", "line redacted", "withheld from packet"],
    distributions: null, sufficiency: "insufficient", context: { lines: 4, complete: true },
    truncation: false, redaction: true, cache: { state: "n/a", ms: 0 },
    packet: packet(["src/config/providerKeys.ts"], 180, 4, 1, ["new line 14 redacted"]) },
  { id: "u12", file: "src/client/reviewSync.js", hunk: 0, line: 48, lane: "attention",
    title: "useReviewSync · line 48", chip: "jev · guard uncertainty", attention: 61, remote: true,
    summary: "A generation-equality guard was added; jev raised attention on whether the early return covers every stale-response path.",
    provenance: ["no analyzer result", "equality guard on a mutable ref", "jev 0.61 attention"],
    distributions: dist(61, 46, 58), sufficiency: "partial", context: { lines: 28, complete: true },
    truncation: false, redaction: false, cache: { state: "live", ms: 173 },
    packet: packet(["src/client/reviewSync.js"], 3640, 28) },
];
