#!/usr/bin/env bun
// builds the self-contained loupe binary: vite-build the client, embed every asset via a
// generated `with { type: "file" }` manifest, inject the version, then compile the manifest.
// Bun 1.3.14 has no compile.assets/--asset CLI, so static file imports are how we embed.

import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { PRODUCT } from "../src/core/product";

const root = join(import.meta.dir, "..");
const clientDir = join(root, "dist", "client");
const generatedDir = join(root, "src", "generated");
const entryFile = join(generatedDir, "standalone.ts");
const version = (JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { version: string }).version;

// 1. build the client
const vite = Bun.spawnSync(["bun", "run", "client:build"], { cwd: root, stdout: "inherit", stderr: "inherit" });
if (vite.exitCode !== 0) throw new Error("vite build failed");

// 2. enumerate dist/client — deterministic, sorted, posix-relative paths
function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(abs));
    else out.push(relative(clientDir, abs).split(sep).join("/"));
  }
  return out;
}
const assets = walk(clientDir).sort();
if (!assets.includes("index.html")) throw new Error("dist/client/index.html missing — did the client build run?");

// 3. generate the embed manifest: one static file import per asset, mapped by client path
const imports = assets.map((rel, i) => `import a${i} from "../../dist/client/${rel}" with { type: "file" };`);
const entries = assets.map((rel, i) => `    ${JSON.stringify(rel)}: a${i},`);
const source = `// AUTO-GENERATED by scripts/build-binary.ts — do not edit.
import { useStandaloneBuild } from "../core/standalone";
import { embeddedAssets } from "../server/assetSource";
import { main } from "../index.ts";
${imports.join("\n")}

useStandaloneBuild({
  version: ${JSON.stringify(version)},
  assets: embeddedAssets({
${entries.join("\n")}
  }),
});

await main();
`;
rmSync(generatedDir, { recursive: true, force: true });
mkdirSync(generatedDir, { recursive: true });
writeFileSync(entryFile, source);

// 4. compile the standalone binary (Bun appends .exe on Windows)
const outfile = join(root, "dist", PRODUCT.name);
const compile = Bun.spawnSync(["bun", "build", entryFile, "--compile", "--outfile", outfile], { cwd: root, stdout: "inherit", stderr: "inherit" });
if (compile.exitCode !== 0) throw new Error("bun compile failed");
console.log(`compiled ${outfile} (v${version}, ${assets.length} embedded assets)`);
