// vite-builds the client and generates the standalone entry (src/generated/standalone.ts) that
// embeds every asset via a `with { type: "file" }` import and injects the version. shared by the
// host build (build-binary.ts) and the cross-target release build (build-release.ts).
// Bun 1.3.14 has no compile.assets/--asset CLI, so static file imports are how we embed.

import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

export interface StandaloneEntry {
  entryFile: string;
  version: string;
  assetCount: number;
}

// deterministic, sorted, posix-relative asset paths under dir.
function walk(base: string, dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(base, abs));
    else out.push(relative(base, abs).split(sep).join("/"));
  }
  return out;
}

export function generateStandaloneEntry(root: string): StandaloneEntry {
  const clientDir = join(root, "dist", "client");
  const generatedDir = join(root, "src", "generated");
  const entryFile = join(generatedDir, "standalone.ts");
  const version = (JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { version: string }).version;
  const licenseText = readFileSync(join(root, "LICENSE"), "utf8");

  const vite = Bun.spawnSync(["bun", "run", "client:build"], { cwd: root, stdout: "inherit", stderr: "inherit" });
  if (vite.exitCode !== 0) throw new Error("vite build failed");

  const assets = walk(clientDir, clientDir).sort();
  if (!assets.includes("index.html")) throw new Error("dist/client/index.html missing — did the client build run?");

  const imports = assets.map((rel, i) => `import a${i} from "../../dist/client/${rel}" with { type: "file" };`);
  const entries = assets.map((rel, i) => `    ${JSON.stringify(rel)}: a${i},`);
  const source = `// AUTO-GENERATED by scripts/generateStandaloneEntry.ts — do not edit.
import { useStandaloneBuild } from "../core/standalone";
import { embeddedAssets } from "../server/assetSource";
import { main } from "../index.ts";
${imports.join("\n")}

useStandaloneBuild({
  version: ${JSON.stringify(version)},
  licenseText: ${JSON.stringify(licenseText)},
  assets: embeddedAssets({
${entries.join("\n")}
  }),
});

await main();
`;
  rmSync(generatedDir, { recursive: true, force: true });
  mkdirSync(generatedDir, { recursive: true });
  writeFileSync(entryFile, source);
  return { entryFile, version, assetCount: assets.length };
}
